colorscheme dracula

map global normal <space> ','
map global normal , '<space>'
map global normal <a-,> '<a-space>'

set global makecmd "make"

eval %sh{kak-lsp --kakoune -s $kak_session}

hook global WinSetOption filetype=(c) %{
    expandtab
    set-option window indentwidth 2
    set-option global softtabstop 2
}

hook global WinSetOption filetype=(rust) %{
    lsp-enable-window
    lsp-hover-enable
    expandtab
    set-option window indentwidth 4
    set-option global softtabstop 4
}

hook global WinSetOption filetype=(scala) %{
    expandtab
    set-option window indentwidth 4
    set-option global softtabstop 4
}

hook global BufNewFile  .*\.ms %{ set buffer filetype 'troff' }
hook global BufOpenFile .*\.ms %{ set buffer filetype 'troff' }

map global user l %{:enter-user-mode lsp<ret>} -docstring "LSP mode"
map global insert <tab> '<a-;>:try lsp-snippets-select-next-placeholders catch %{ execute-keys -with-hooks <lt>tab> }<ret>' -docstring 'Select next snippet placeholder'
map global object a '<a-semicolon>lsp-object<ret>' -docstring 'LSP any symbol'
map global object <a-a> '<a-semicolon>lsp-object<ret>' -docstring 'LSP any symbol'
map global object e '<a-semicolon>lsp-object Function Method<ret>' -docstring 'LSP function or method'
map global object k '<a-semicolon>lsp-object Class Interface Struct<ret>' -docstring 'LSP class interface or struct'
map global object d '<a-semicolon>lsp-diagnostic-object --include-warnings<ret>' -docstring 'LSP errors and warnings'
map global object D '<a-semicolon>lsp-diagnostic-object<ret>' -docstring 'LSP errors'


hook global RegisterModified '"' %{ nop %sh{
      printf %s "$kak_main_reg_dquote" | xsel --input --clipboard
}}

hook global BufCreate .* %{
    add-highlighter buffer/lines0 number-lines -relative
}

hook global ModeChange push:normal:insert %{
    remove-highlighter buffer/lines0
    add-highlighter buffer/lines1 number-lines
}
hook global ModeChange pop:insert:normal  %{
    remove-highlighter buffer/lines1
    add-highlighter buffer/lines0 number-lines -relative
}

hook global -once ModuleLoaded c-family %{
      define-command -override -hidden c-family-indent-on-opening-curly-brace nop
}

add-highlighter global/ show-whitespaces -tab '│' -tabpad '╌'
