colorscheme dracula

set global makecmd "xmake"

hook global RegisterModified '"' %{ nop %sh{
      printf %s "$kak_main_reg_dquote" | xsel --input --clipboard
}}

hook global BufCreate .* %{
    add-highlighter buffer/lines0 number-lines -relative
}

hook global ModeChange push:normal:insert %{
    remove-highlighter buffer/lines0
    add-highlighter buffer/lines1 number-lines
}
hook global ModeChange pop:insert:normal  %{
    remove-highlighter buffer/lines1
    add-highlighter buffer/lines0 number-lines -relative
}

add-highlighter global/ show-whitespaces -tab '│' -tabpad '╌'
